### ISSUE TITLE
Node.js 16

### ISSUE THREAD

**Issue by orchid00** [petems/csv-to-md-table-action#201]
Hi @petems,
Thanks for the action,
When I tried to run it recently it gave me this message:

Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: petems/csv-to-md-table-action

Do you think you can do the update?
Thanks!

**Comment by petems** [comment]
Closed via https://github.com/petems/csv-to-md-table-action/commit/e5b009fd97d5e9896b47b660581bf78272f5ad3b

**Comment by petems** [comment]
Released in https://github.com/petems/csv-to-md-table-action/releases/tag/v3.0.0
