### ISSUE TITLE
Upgrade Node.js to 20

### ISSUE THREAD

**Issue by mariuspaliga** [petems/csv-to-md-table-action#243]
Hi, similarly to [here](https://github.com/petems/csv-to-md-table-action/issues/201), would it be possible to upgrade to node 20, please?
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

Currently, the GitHub gives the following warning:
```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: petems/csv-to-md-table-action@v3.0.0. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```

**Comment by petems** [comment]
Man these deprecations come fast! I'll bump to node 20, test and push out a build tonight or tomorrow

**Comment by petems** [comment]
Just bumped to Node.js 20, released as https://github.com/petems/csv-to-md-table-action/releases/tag/v4.0.0 can you see if the deprecation message is gone for you?

**Comment by mariuspaliga** [comment]
Yes, the deprecation warning is gone. Thanks!

**Comment by petems** [comment]
👍🏻 awesome
